server:
  port: 8081
  shutdown: "graceful"

spring:
  lifecycle:
    timeout-per-shutdown-phase: "1m"


# Monitoring, readness, liveness, logging
management:
  endpoints:
    web:
      base-path: "/monitoring"
      exposure:
        include: health, info, prometheus, metrics, loggers, shutdown
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
    loggers:
      enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true

info:
  app:
    name: "@artifactId@"
    version: "@version@"
    encoding: "@project.build.sourceEncoding@"

logging:
  pattern:
    console: "%magenta(%d{ISO8601}) %highlight(%-5level) [%yellow(%t)] %replace(RqUid=%X{RqUid}){'^RqUid=$', ''} %cyan(%C{1.}): %msg %n%throwable"
  level:
    com.fedorizvekov.${firstModuleName}: INFO
    org.springframework: INFO