version: '3.9'

networks:
  minio_network:
    driver: bridge

services:

  minio_application:
    image: bellsoft/liberica-openjdk-alpine:17.0.7
    container_name: minio_application
    restart: unless-stopped
    volumes:
      - ../config/certs/client/minio_app/keystore.p12:/app/certs/keystore.p12
      - ../config/certs/client/minio_app/truststore.p12:/app/certs/truststore.p12
      - ./target:/app
    working_dir: /app
    mem_limit: 200m
    mem_reservation: 200m
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ENABLE_HTTPS: true
      MINIO_ACCESS_KEY: Q0PNkPIVzI0Ehog5
      MINIO_SECRET_KEY: 7pESohnGQC6hwGKQbqx6xDWc1s4e912m
      SSL_KEY_ALIAS: minio
      SSL_KEY_STORE_TYPE: PKCS12
      SSL_KEY_STORE: /app/certs/keystore.p12
      SSL_KEY_STORE_PASSWORD: password_keystore
      SSL_TRUST_STORE: /app/certs/truststore.p12
      SSL_TRUST_STORE_PASSWORD: password_truststore
    command: java -Xmx200m -jar minio-1.0.0-SNAPSHOT.jar
    ports:
      - 8081:8081
    networks:
      - minio_network
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: unless-stopped
    volumes:
      - ../config/certs/server/minio:/root/.minio/certs
      - ../../../minio_storage/data:/data
    mem_limit: 300m
    mem_reservation: 300m
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: ZmNQnMAKt9
      MINIO_CERT_PASSWD: password_server_key
    command: server --console-address ":9001" --address ":9000" /data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio_network